### PR TITLE
Fix build on MacOS

### LINKED ISSUE #42: Fix MacOS build

### PR DESCRIPTION
**Pull request by AndrejMitrovic**
Fixes #42

### CODE REVIEW

File: src/dtk/loader.d [hunk 1]
```diff
@@ -178,6 +178,7 @@ private void loadSharedLibs ()
 
     foreach (pair; paths)
     {
+        import std.stdio;
```
Comment (AndrejMitrovic) [inline src/dtk/loader.d]: extra import

File: src/dtk/dispatch.d [hunk 2]
```diff
@@ -281,7 +281,7 @@ static:
                 6 => Widget mouse X position
                 7 => Desktop mouse X position
                 8 => Desktop mouse Y position
-                9 => Timestamp
+                9 => Timestamp (unreliable)
```
Comment (AndrejMitrovic) [inline src/dtk/dispatch.d]: 9 will be an invalid index, so we should remove this comment.

File: src/dtk/dispatch.d [hunk 3]
```diff
@@ -1089,7 +1088,7 @@ private Widget getTclWidget(const(Tcl_Obj)* tclObj)
     return Widget.lookupWidgetPath(tclObj.tclPeekString());
 }
 
-/** Extract the timestamp from the tcl_Obj object. */
+/** Extract the timestamp from the tcl_Obj object. Note: unreliable. */
```
Comment (AndrejMitrovic) [inline src/dtk/dispatch.d]: This should just be removed if it's unreliable.

**Comment by AndrejMitrovic** [comment]
It looks like there might be something broken with the timestamp change commit. Maybe it breaks some tests. The tests never finish.

**Comment by AndrejMitrovic** [comment]
Aha, we failed to update `assert(tclArr.length == 10, tclArr.length.text);`
